mailgroup.type.*:
  type: config_entity
  label: 'Mail group type'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    label:
      type: label
      label: 'Name'
    description:
      type: 'text'
      label: 'Description'
