<?php

/**
 * @file
 * Contains azhealthclub_step_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function azhealthclub_step_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the azhealthclub_step_login module.
    case 'help.page.azhealthclub_step_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Step login') . '</p>';
      return $output;

    default:
  }
}

