<?php

/**
 * @file
 * Contains azhealthclub_step_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function azhealthclub_step_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the azhealthclub_step_login module.
    case 'help.page.azhealthclub_step_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Step login') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function azhealthclub_step_login_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (!$form_state->has('page_num')) {
    $form_state->set('page_num', 1);
  }
  // add member profile field in register form
  // todo add form element from profile fileds
  $form['field_zh_name'] = [
    '#type' => 'textfield',
    '#title' => '中文姓名',
  ];
  $form['field_en_name'] = [
    '#type' => 'textfield',
    '#title' => '英文姓名',
  ];
  $form['field_where'] = [
    '#type' => 'checkboxes',
    '#options' => [1=>1, 2 =>2],
  ];

  $pages = [
    1 => [
      'mail',
      'name',
      'account',
      'field_attention',
    ],
    2 => [
      'field_zh_name',
      'field_en_name',
    ],
    3 => [
      'field_where',
      'actions',
    ],
  ];
  if (!$form_state->has('pages_fields')) {
    $form_state->set('pages_fields', $pages);
  }

  // Validate the fields of the appropriate steps.
  $validation = [];

  // Disable all the fields to begin.
  foreach ($pages as $page => $fields) {
    if ($page != $form_state->get('page_num')) {
      foreach ($fields as $field) {
        $form[$field]['#access'] = FALSE;
      }
    }
    else {
      foreach ($fields as $field) {
        array_push($validation, [$field]);
      }
    }
  }


  // Add our custom validation function to the start of the array.
  array_unshift($form['#validate'], 'azhealthclub_step_login_user_register_pre_validate');

  $form['azhealthclub_step_login_actions'] = [
    '#type' => 'actions',
    '#weight' => 100,
  ];

  $form['azhealthclub_step_login_actions']['next'] = [
    '#type' => 'submit',
    '#value' => t('Next'),
    '#submit' => [
      'azhealthclub_step_login_register_next_previous_form_submit',
    ],
    '#limit_validation_errors' => $validation,
    '#access' => FALSE,
    '#weight' => 1,
  ];

  $form['azhealthclub_step_login_actions']['previous'] = [
    '#type' => 'submit',
    '#value' => t('Back'),
    '#submit' => [
      'azhealthclub_step_login_register_next_previous_form_submit',
    ],
    '#access' => FALSE,
    '#limit_validation_errors' => [],
  ];

  switch ($form_state->get('page_num')) {
    case 1:
      // Allow access to the pages on this page.
      foreach ($pages[$form_state->get('page_num')] as $form_key) {
        $form[$form_key]['#access'] = TRUE;
      }

      // Enable our next button.
      $form['azhealthclub_step_login_actions']['next']['#access'] = TRUE;
      break;

    case 2:
      $page_values = $form_state->get('page_values');

      // Enable our next button.
      $form['azhealthclub_step_login_actions']['previous']['#access'] = TRUE;
      $form['azhealthclub_step_login_actions']['next']['#access'] = TRUE;
      break;

    case 3:
      $page_values = $form_state->get('page_values');

      // Add our previous buttons.
      $form['azhealthclub_step_login_actions']['next']['#access'] = FALSE;
      $form['azhealthclub_step_login_actions']['previous']['#access'] = TRUE;
      break;
  }
}


function azhealthclub_step_login_register_next_previous_form_submit($form, Drupal\Core\Form\FormStateInterface $form_state) {

  // Get the current page that was submitted.
  $current_page = $form_state->get('page_num');

  // Get the fields for the pages.
  // These are the same as the $pages variable in the form_alter.
  // I've excluded them here for brevity.
  $fields = $form_state->get('pages_fields');

  // Setup our page values variable.
  if (!$form_state->get('page_values')){
    $page_values = [];
  }

  if ($form_state->getValue('next')) {
    // Add the values to the page_value array.
    foreach ($fields[$current_page] as $key) {
      $page_values[$current_page][$key] = $form_state->getValue($key);
    }
    // Increment the page number.
    $current_page++;
  }
  else if ($form_state->getValue('previous')) {
    // Discard the values the page_value array.
    foreach ($fields[$current_page] as $key) {
      $form_state->setValue($key, $page_values[$current_page][$key]);
      unset($page_values[$current_page][$key]);
    }
    // Decrement the page number.
    $current_page--;
  }

  $form_state
    ->set('page_num', $current_page)
    ->set('page_values', $page_values)
    ->setRebuild(TRUE);
}




function azhealthclub_step_login_user_register_pre_validate($form, Drupal\Core\Form\FormStateInterface $form_state) {
  // Load the submitted values.
  if (!$form_state->get('page_values')){
    $page_values = [];
  }
  else {
    $page_values = $form_state->get('page_values');
  }

  $submitted_values = $form_state->getValues();

  // Put all the paged values back into the form_state values.
  foreach ($page_values as $page_num => $fields) {
    foreach ($fields as $key => $value) {
      $submitted_values[$key] = $value;
    }
  }

  // Save the form_state values for further processing.
  $form_state->setValues($submitted_values);
}
