<?php

/**
 * @file
 * Contains azhealthclub_modify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\views\ViewExecutable;
use Drupal\Core\StringTranslation;

/**
 * Implements hook_help().
 */
function azhealthclub_modify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the azhealthclub_modify module.
    case 'help.page.azhealthclub_modify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Some modify code for azhealthclub') . '</p>';
      return $output;

    default:
  }
}


/**
 * @param $key
 * @param $message
 * @param $params
 *  hook_mail
 */
function azhealthclub_modify_mail($key, &$message, $params) {
  if ($key == 'smtp-test') {
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['body'];
  }
}

function azhealthclub_modify_theme()
{
 return [
   'azhealthclub_ClinicalSearchResult'=> [
     'variables' => [
       'variables'=>[]
     ]
   ],
   'azhealthclub_contact'=> [
     'variables' => [
       'variables'=>[]
     ]
   ],
   'az_clinical_filter_block'=>[
     'variables' => [
       'variables' => []
     ]
   ],
   'azhealthclub_welcome'=>[
     'variables' => [
       'variables' => []
     ]
   ],
   'azhealthclub_dashboard'=>[
     'variables' => [
       'variables' => []
     ]
   ],
   'az_header_right_block'=>[
     'variables' => [
       'variables' => []
     ]
   ],
    'azhealthclub_memberclinal' =>[
      'variables' => [
        'variables' => []
      ]
    ]
 ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function azhealthclub_modify_menu_local_tasks_alter(&$data, $route_name, \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability) {
  $user_pages = ['user.login', 'user.register', 'user.pass'];
  if (in_array($route_name, $user_pages) && isset($data['tabs'][0])) {
    // Remove all tabs from user login form.
    foreach ($data['tabs'][0] as $key => $tab) {
      $data['tabs'][0][$key]['#access'] = FALSE;
    }
  }
}


/**
 * Implements hook_form_alter().
 */
function azhealthclub_modify_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "user_login_form") {
    $form['#prefix'] = '<div><div class="free-apply">免費申請加入「康心摯友會」</div>';
    $form['#suffix'] = '</div>';

    $form["name"]["#title"] = '';
    $form["name"]["#description"] = '';
    $form['name']['#attributes']['placeholder'] = '登入名稱';
    $form["pass"]["#title"] = '';

    $urlGenerator = \Drupal::urlGenerator();
    $url = $urlGenerator->generateFromRoute('user.pass');
    $form["pass"]["#description"] = '<a href="' . $url . '">忘記密碼</a>';
    $form['pass']['#attributes']['placeholder'] = '密碼';

    $form["actions"]["submit"]["#value"] = '登入';
    $form["actions"]["register"] = [
      '#title' => '加入康心摯友會',
      '#type' => 'link',
      '#url' => \Drupal\Core\Url::fromRoute('azhealthclub_step_login.multistep_one'),
      '#attributes'=> [
        'class' => ['btn'],
      ],
    ];
  }

}
//webform auto send
//function azhealthclub_modify_webform_handler_invoke_post_save_alter(\Drupal\webform\Plugin\WebformHandlerInterface $handler, array &$args) {
//  $webform = $handler->getWebform();
//  $webform_id = $webform->id();
//  if($webform_id == "contact"){
//    try {
//      $mailManager = \Drupal::service('plugin.manager.mail');
//      $Name =  $handler->getWebformSubmission()->getElementData("name");
//      $Email =  $handler->getWebformSubmission()->getElementData("email");
//      $subject =  $handler->getWebformSubmission()->getElementData("subject");
//      $message =  $handler->getWebformSubmission()->getElementData("message");
//      $params['subject'] = $subject;
//      $params['body'] = $message;
//      $params['headers'] = [
//        'content-type' => 'text/plain',
//      ];
//      $mailManager->mail('azhealthclub', 'smtp-test', $Email,'en' , $params,NULL,true);
//      \Drupal::logger('contact webform')->notice('email notice' );
//    }catch (Exception $e){
//      \Drupal::logger('contact webform')->error('email error' . json_encode($e));
//    }
//  }
//}


/**
 * Implements hook_preprocess().
 */
function azhealthclub_modify_preprocess(&$variables, $hook) {
  if ($hook == 'page_title') {
    $current_url = \Drupal\Core\Url::fromRoute('<current>');
    $url = $current_url->getInternalPath();
    if($url == 'user/login') {
      $variables['title'] = '登入/加入 康心摯友會';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function azhealthclub_modify_form_multistep_form_one_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $member = \Drupal::currentUser();
  if ($member->isAnonymous()) {
    return;
  }
  $storage = \Drupal::entityTypeManager()->getStorage('profile');
  $profile = $storage->loadByUser($member, 'member');
  $phone = $profile->get('field_phone')->getValue()[0]['value'];
  $email = $member->getEmail();
  $account = $member->getAccount();
  $pass = $account->pass;
  $attention1 = array_column($profile->get('field_attention1')->getValue(), 'value');

  $form['line1']['phone']['#default_value'] = $phone;
  $form['line1']['email']['#default_value'] = $email;
  $form['line2']['pass'] = [
    '#type' => 'value',
    '#value' => $pass
  ];
  $form['line2']['confirm_pass'] = [
    '#type' => 'value',
    '#value' => $pass
  ];
  $form['attention1']['#default_value'] = $attention1;
  $form['attention1']['#disabled'] = TRUE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function azhealthclub_modify_form_multistep_form_two_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $member = \Drupal::currentUser();
  if ($member->isAnonymous()) {
    return;
  }
  $storage = \Drupal::entityTypeManager()->getStorage('profile');
  $profile = $storage->loadByUser($member, 'member');
  $zh_name = $profile->get('field_zh_name')->getValue()[0]['value'];
  $en_name = $profile->get('field_en_name')->getValue()[0]['value'];
  $identification_last4num = $profile->get('field_identification_last4num')->getValue()[0]['value'];
  $birthday = $profile->get('field_birthday')->getValue()[0]['value'];
  $gender = $profile->get('field_gender')->getValue()[0]['value'];
  $attention2 = array_column($profile->get('field_attention2')->getValue(), 'value');
  $communication_mode = array_column($profile->get('field_communication_mode')->getValue(), 'value');

  $form['zh_name']['#default_value'] = $zh_name;
  $form['en_name']['#default_value'] = $en_name;
  $form['identification_last4num']['#default_value'] = $identification_last4num;
  $form['birthday']['#default_value'] = $birthday;
  $form['gender']['#default_value'] = $gender;
  $form['attention2']['#default_value'] = $attention2;
  $form['communication_mode']['#default_value'] = $communication_mode;
  $form['actions']['previous'] ['#url'] = Url::fromRoute('azhealthclub_modify.profile1');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function azhealthclub_modify_form_multistep_form_three_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $member = \Drupal::currentUser();
  if ($member->isAnonymous()) {
    return;
  }
  $storage = \Drupal::entityTypeManager()->getStorage('profile');
  $profile = $storage->loadByUser($member, 'member');
  $no_medicine_using_values = $profile->get('field_no_medicine_using')->getValue();
  $no_medicine_using = isset($no_medicine_using_values[0]['value']) ? $no_medicine_using_values[0]['value'] : '';
  $ta_type = array_column($profile->get('field_ta_type')->getValue(), 'value');
  $medicine_using = array_column($profile->get('field_medicine_using')->getValue(), 'value');
  $where1 = array_column($profile->get('field_where1')->getValue(), 'value');
  $where2 = array_column($profile->get('field_where2')->getValue(), 'value');

  $form['no_medicine_using']['#default_value'] = $no_medicine_using;
  $form['ta_type']['#default_value'] = $ta_type;
  $form['medicine_using']['#default_value'] = $medicine_using;
  $form['where1']['#default_value'] = $where1;
  $form['where2']['#default_value'] = $where2;
  $form['actions']['previous'] ['#url'] = Url::fromRoute('azhealthclub_modify.profile2');
}
