<?php

/**
 * @file
 * Contains azhealthclub_modify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function azhealthclub_modify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the azhealthclub_modify module.
    case 'help.page.azhealthclub_modify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Some modify code for azhealthclub') . '</p>';
      return $output;

    default:
  }
}

function azhealthclub_modify_theme()
{
 return [
   'azhealthclub_contact'=> [
     'variables' => [
       'variables'=>[]
     ]
   ]
 ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function azhealthclub_modify_menu_local_tasks_alter(&$data, $route_name, \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability) {
  $user_pages = ['user.login', 'user.register', 'user.pass'];
  if (in_array($route_name, $user_pages) && isset($data['tabs'][0])) {
    // Remove all tabs from user login form.
    foreach ($data['tabs'][0] as $key => $tab) {
      $data['tabs'][0][$key]['#access'] = FALSE;
    }
  }
}


/**
 * Implements hook_form_alter().
 */
function azhealthclub_modify_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "user_login_form") {
    $form["name"]["#title"] = '';
    $form["name"]["#description"] = '';
    $form['name']['#attributes']['placeholder'] = '登入名稱';
    $form["pass"]["#title"] = '';
    $form["pass"]["#description"] = '';
    $form['pass']['#attributes']['placeholder'] = '密碼';
  }
}
