<?php

/**
 * @file
 * Contains \Drupal\azhealthclub_step_login\Form\MultistepFormBase.
 */

namespace Drupal\azhealthclub_modify\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Session\SessionManagerInterface;
use Drupal\Core\TempStore\PrivateTempStoreFactory;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\user\Entity\User;
use Drupal\profile\Entity\Profile;

class CancelSubscribeForm extends FormBase {


  /**
   * {@inheritdoc}.
   */
  public function getFormId() {
    return 'cancel_subscribe_form';
  }

  /**
   * {@inheritdoc}.
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form = [];
    $form['title'] = [
      '#markup' => '<h1>取消訂閱-康心摯友會資訊</h1><div class="az-cancel-v-line"></div>'
    ];
    $form['your_email'] = [
      '#markup' => '<span>你的電郵地址：</span><span class="az-can-mail">email@example.com</span>'
    ];

    $taxonomy_terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('ta_type');
    $ta_type = [];
    foreach ($taxonomy_terms as $term) {
      if ($term->depth == 0)  {
        $ta_type[$term->tid] = $term->name ;
      }
    }
    $form['ta_type'] = [
      '#type' => 'checkboxes',
      '#title' => '<h5>我希望取消以下資訊範疇</h5>',
      '#options'=> $ta_type,
    ];

    $form['actions']['#type'] = 'actions';
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => '取消訂閱',
      '#button_type' => 'primary',
      '#weight' => 10,
    ];

    return $form;
  }


  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $currentUser = \Drupal::currentUser();
    // todo: some function
  }


  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
